
import { Translation, Language, ShootDay } from './types';

const COMMON_DEPT = {
  production: "Production",
  direction: "Direction",
  camera: "Camera",
  lighting: "Lighting / Grip",
  sound: "Sound",
  art: "Art Dept / Props",
  costume: "Costume",
  makeup: "Hair & Makeup",
  catering: "Catering",
  cast: "Cast / Stunts",
  other: "Other"
};

const COMMON_DEPT_DE = {
  production: "Produktion",
  direction: "Regie",
  camera: "Kamera",
  lighting: "Licht / Bühne",
  sound: "Ton",
  art: "Szenenbild / Requisite",
  costume: "Kostüm",
  makeup: "Maske",
  catering: "Catering",
  cast: "Darsteller / Stunts",
  other: "Sonstiges"
};

export const INITIAL_SCHEDULE: ShootDay[] = [
  { day: 1, date: new Date().toISOString().split('T')[0] }
];

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    appSub: "Safe on Set",
    role: "Production Manager",
    hMood: "LIVE MOOD",
    hTrend: "TREND HISTORY",
    hAccess: "ACCESS & ACTIONS",
    pdf: "PDF",
    email: "Email Address",
    inbox: "Feedback",
    inboxTitle: "Written Feedback",
    mobTitle: "TODAY'S FEEDBACK",
    mobQuest: "How did you feel about today's shoot?",
    happy: "Happy 😊",
    stress: "Stressed 😓",
    submit: "Submit",
    compTitle: "⚠️ We are sorry to hear that.",
    compDesc: "Please tell us what happened so we can help.",
    compContact: "Contact (Required)",
    alert: "Feedback submitted!",
    dir: "ltr",
    day: "Day",
    today: "Today",
    explTitle100: "Status: Excellent",
    explText100: "Everything is in order, crew feels well.",
    explTitle90: "Status: Attention Required",
    explText90: "Negative feedback received recently.",
    explTitle80: "Status: Urgent Action",
    explText80: "Immediate action required.",
    imprBtn: "Legal Notice",
    imprTitle: "Legal Notice",
    imprText: "Trustory GmbH...",
    privacyTitle: "Privacy Policy",
    privacyText: "Data Protection...",
    termsTitle: "Terms of Service",
    termsText: "General Terms...",
    votingClosed: "Voting Closed",
    votingClosedDesc: "Today is not a scheduled shooting day.",
    btnPositive: "EVERYTHING IS FINE",
    btnNegative: "NEGATIVE EXPERIENCE",
    disclaimerText: "Did you feel comfortable on set today?",
    selectDept: "Select Department (Optional)",
    deptLabel: "Department",
    depts: COMMON_DEPT,
    adminLogin: "Admin Login",
    otpSent: "Code sent to email!",
    otpPlaceholder: "Enter 6-digit Code",
    sendCode: "Request Login Code",
    verifyCode: "Verify & Login",
    backToEmail: "Change Email",
    adminDash: "Admin Dashboard",
    addProd: "Add Production",
    prodName: "Production Name",
    prodCoord: "Coordinator Name",
    prodEmail: "Coordinator Email",
    invite: "Invite",
    status: "Status",
    logout: "Logout",
    thankYou: "Thank You!",
    voteRegistered: "Your feedback has been registered.",
    alreadyVoted: "Feedback Received",
    alreadyVotedDesc: "You have already submitted feedback for today.",
    viewStats: "Stats",
    prodStats: "Production Statistics",
    currentScore: "Current Score",
    recentIncidents: "Recent Incidents",
    noIncidents: "No critical incidents reported.",
    close: "Close",
    manage: "Manage",
    manageProd: "Manage Production",
    endProd: "End Production",
    reactivateProd: "Reactivate",
    prodEnded: "Production Finished",
    teamMembers: "Team Access",
    addMember: "Add Team Member",
    roleLabel: "Role",
    nameLabel: "Name",
    emailLabel: "Email",
    add: "Add",
    maxMembers: "Max 4 additional members reached",
    generalInfo: "General Information",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    inviteSent: "Invitation sent!",
    registerProd: "Register Production",
    regTitle: "Official Registration",
    regDesc: "Submit your production details for verification and activation.",
    countryLabel: "Country",
    selectCountry: "Select Country",
    otherCountryPlaceholder: "Enter Country",
    period: "Production Period",
    periodStart: "From (MM/YYYY)",
    periodEnd: "To (MM/YYYY)",
    officeAddr: "Office Address",
    billingAddr: "Billing Address",
    trustSection: "Safety Contact",
    optional: "(Optional)",
    trustThemis: "Themis Partner",
    trustInternal: "Internal Contact",
    trustInternalName: "Contact Info",
    regSuccess: "SUCCESSFULLY SUBMITTED",
    regSuccessDesc: "Your data has been received. Our team will verify and activate your production within 24 hours.",
    tabSchedule: "Schedule",
    tabDetails: "Details",
    landHero: "Safe Sets. Better Stories.",
    landSub: "The specialized software for anti-harassment on film sets. Your digital trust center – expert-vetted and supported by major film and streaming providers.",
    landCTA: "Start Now",
    feat1Title: "Anonymous Feedback",
    feat1Desc: "Empower your crew.",
    feat1More: "Advanced encryption.",
    feat2Title: "Real-Time Insights",
    feat2Desc: "Monitor atmosphere.",
    feat2More: "Dashboard metrics.",
    feat3Title: "Secure & Trusted",
    feat3Desc: "GDPR compliant.",
    feat3More: "Strict data standards.",
    howTitle: "How it works",
    how1: "Register",
    how2: "Print QR",
    how3: "Crew Votes",
    trustBadge1: "Version 2.0 • New from 2026",
    trustBadge2: "Now live in UK, UAE, Germany, and across the EU.",
    trustSecTitle: "Never Alone.",
    trustSecSub: "Professional support integrated.",
    trustSecFeat1: "Themis Connection.",
    trustSecFeat2: "24/7 Availability.",
    trustSecFeat3: "Anonymous Hotline.",
    trustCardTitle: "Trust Center",
    trustCardName: "Themis Advice Center",
    trustCardBtn: "Contact Support",
    deptInsights: "Department Insights",
    markResolved: "Resolve Feedback",
    testAccess: "Test Access",
    enterTestCode: "Enter Code",
    requestTestAccess: "Request Access",
    pendingRequests: "Requests Management",
    approve: "Approve",
    reject: "Reject",
    testAccountInfo: "This is a test account. Data will not be saved."
  },
  de: {
    appSub: "Safe on Set",
    role: "Produktionsleitung",
    hMood: "AKTUELLE STIMMUNG",
    hTrend: "TREND VERLAUF",
    hAccess: "ZUGANG & AKTIONEN",
    pdf: "PDF",
    email: "Email-Adresse",
    inbox: "Feedback",
    inboxTitle: "Schriftliches Feedback",
    mobTitle: "HEUTIGES FEEDBACK",
    mobQuest: "Wie hast du den heutigen Drehtag empfunden?",
    happy: "Zufrieden 😊",
    stress: "Gestresst 😓",
    submit: "Absenden",
    compTitle: "⚠️ Das tut uns leid.",
    compDesc: "Bitte sag uns was passiert ist, damit wir helfen können.",
    compContact: "Kontakt (Erforderlich)",
    alert: "Feedback gesendet!",
    dir: "ltr",
    day: "Tag",
    today: "Heute",
    explTitle100: "Status: Ausgezeichnet",
    explText100: "Alles ist in Ordnung, Mitarbeiter fühlen sich wohl.",
    explTitle90: "Status: Aufmerksamkeit erforderlich",
    explText90: "Ein negatives Feedback wurde kürzlich abgegeben.",
    explTitle80: "Status: Dringende Aktion",
    explText80: "Sofortige Aktion erforderlich.",
    imprBtn: "Impressum",
    imprTitle: "Impressum",
    imprText: "Trustory GmbH...",
    privacyTitle: "Datenschutzerklärung",
    privacyText: "Hinweise zum Datenschutz...",
    termsTitle: "AGB",
    termsText: "Allgemeine Bedingungen...",
    votingClosed: "Abstimmung Geschlossen",
    votingClosedDesc: "Heute ist kein geplanter Drehtag.",
    btnPositive: "ALLES IN ORDNUNG",
    btnNegative: "NEGATIVE ERFAHRUNG",
    disclaimerText: "Hast du dich heute am Set wohlgefühlt?",
    selectDept: "Abteilung wählen (Optional)",
    deptLabel: "Abteilung",
    depts: COMMON_DEPT_DE,
    adminLogin: "Admin Login",
    otpSent: "Code an Email gesendet!",
    otpPlaceholder: "6-stelligen Code eingeben",
    sendCode: "Login-Code anfordern",
    verifyCode: "Verifizieren & Login",
    backToEmail: "Email ändern",
    adminDash: "Admin Übersicht",
    addProd: "Produktion anlegen",
    prodName: "Produktions-Titel",
    prodCoord: "Name Koordinator/in",
    prodEmail: "Email Koordinator/in",
    invite: "Einladen",
    status: "Status",
    logout: "Abmelden",
    thankYou: "Danke!",
    voteRegistered: "Dein Feedback wurde registriert.",
    alreadyVoted: "Feedback erhalten",
    alreadyVotedDesc: "Du hast heute bereits Feedback abgegeben.",
    viewStats: "Statistik",
    prodStats: "Produktions-Statistik",
    currentScore: "Aktueller Score",
    recentIncidents: "Kürzliche Vorfälle",
    noIncidents: "Keine kritischen Vorfälle gemeldet.",
    close: "Schließen",
    manage: "Verwalten",
    manageProd: "Produktion verwalten",
    endProd: "Produktion beenden",
    reactivateProd: "Reaktivieren",
    prodEnded: "Produktion beendet",
    teamMembers: "Team Zugang",
    addMember: "Team-Mitglied hinzufügen",
    roleLabel: "Rolle",
    nameLabel: "Name",
    emailLabel: "Email",
    add: "Hinzufügen",
    maxMembers: "Maximal 4 weitere Mitglieder erreicht",
    generalInfo: "Allgemeine Informationen",
    edit: "Bearbeiten",
    save: "Speichern",
    cancel: "Abbrechen",
    inviteSent: "Einladung gesendet!",
    registerProd: "Produktion Registrieren",
    regTitle: "Offizielle Registrierung",
    regDesc: "Übermitteln Sie Ihre Produktionsdaten zur Verifizierung und Freischaltung.",
    countryLabel: "Land",
    selectCountry: "Wählen",
    otherCountryPlaceholder: "Eingeben",
    period: "Produktions-Zeitraum",
    periodStart: "Von (MM/JJJJ)",
    periodEnd: "Bis (MM/JJJJ)",
    officeAddr: "Anschrift Büro",
    billingAddr: "Rechnungsadresse",
    trustSection: "Vertrauensstelle",
    optional: "(Optional)",
    trustThemis: "Wir arbeiten mit Themis",
    trustInternal: "Interne Person",
    trustInternalName: "Kontaktinfos",
    regSuccess: "ERFOLGREICH ÜBERMITTELT",
    regSuccessDesc: "Ihre Daten sind eingegangen. Unser Team wird die Produktion nach Prüfung innerhalb von 24h freischalten.",
    tabSchedule: "Drehplan",
    tabDetails: "Details",
    landHero: "Sichere Sets. Bessere Filme.",
    landSub: "Die spezialisierte Software für Anti-Harassment am Filmset. Die digitale Vertrauensstelle – von Experten geprüft und von führenden Film- und Streaminganbietern unterstützt.",
    landCTA: "Jetzt Starten",
    feat1Title: "Anonymes Feedback",
    feat1Desc: "Crew stärken.",
    feat1More: "Verschlüsselt.",
    feat2Title: "Echtzeit-Einblicke",
    feat2Desc: "Atmosphäre überwachen.",
    feat2More: "Live Metriken.",
    feat3Title: "Sicher & Vertrauenswürdig",
    feat3Desc: "DSGVO konform.",
    feat3More: "Server in Deutschland.",
    howTitle: "So geht's",
    how1: "Registrieren",
    how2: "QR drucken",
    how3: "Crew votet",
    trustBadge1: "Version 2.0 • Neu ab 2026",
    trustBadge2: "Jetzt live in UK, VAE, Deutschland und in der gesamten EU.",
    trustSecTitle: "Nie Allein.",
    trustSecSub: "Support integriert.",
    trustSecFeat1: "Themis-Anbindung.",
    trustSecFeat2: "24/7 Hilfe.",
    trustSecFeat3: "Hotline.",
    trustCardTitle: "Vertrauensstelle",
    trustCardName: "Themis Beratung",
    trustCardBtn: "Kontakt aufnehmen",
    deptInsights: "Abteilungs-Einblick",
    markResolved: "Feedback klären",
    testAccess: "Test-Zugang",
    enterTestCode: "Code eingeben",
    requestTestAccess: "Zugang anfragen",
    pendingRequests: "Anfragen Verwalten",
    approve: "Genehmigen",
    reject: "Ablehnen",
    testAccountInfo: "Test-Account. Daten werden nicht gespeichert."
  },
  ar: {
    appSub: "Safe on Set",
    role: "مدير الإنتاج",
    hMood: "الحالة المزاجية المباشرة",
    hTrend: "تاريخ الاتجاهات",
    hAccess: "الوصول والإجراءات",
    pdf: "PDF",
    email: "Email Address",
    inbox: "التعليقات",
    inboxTitle: "التعليقات المكتوبة",
    mobTitle: "تعليقات اليوم",
    mobQuest: "كيف شعرت تجاه تصوير اليوم؟",
    happy: "سعيد 😊",
    stress: "مضغوط 😓",
    submit: "إرسال",
    compTitle: "⚠️ نأسف لسماع ذلك.",
    compDesc: "يرجى إخبارنا بما حدث لنتمكن من المساعدة.",
    compContact: "الاتصال (مطلوب)",
    alert: "تم إرسال التعليق!",
    dir: "rtl",
    day: "يوم",
    today: "اليوم",
    explTitle100: "الحالة: ممتاز",
    explText100: "كل شيء على ما يرام، الطاقم يشعر بالراحة.",
    explTitle90: "الحالة: انتباه مطلوب",
    explText90: "تم استلام تعليقات سلبية مؤخرًا.",
    explTitle80: "الحالة: إجراء عاجل",
    explText80: "مطلوب إجراء فوري.",
    imprBtn: "إشعار قانوني",
    imprTitle: "إشعار قانوني",
    imprText: "Trustory GmbH",
    privacyTitle: "سياسة الخصوصية",
    privacyText: "حماية البيانات...",
    termsTitle: "شروط الخدمة",
    termsText: "الشروط العامة...",
    votingClosed: "التصويت مغلق",
    votingClosedDesc: "اليوم ليس يوم تصوير مجدول.",
    btnPositive: "كل شيء على ما يرام",
    btnNegative: "تجربة سلبية",
    disclaimerText: "هل شعرت بالراحة في موقع التصوير اليوم؟",
    selectDept: "اختر القسم (اختياري)",
    deptLabel: "القسم",
    depts: COMMON_DEPT,
    adminLogin: "تسجيل دخول المشرف",
    otpSent: "تم إرسال الرمز!",
    otpPlaceholder: "أدخل الرمز",
    sendCode: "Request Login Code",
    verifyCode: "التحقق والدخول",
    backToEmail: "تغيير البريد الإلكتروني",
    adminDash: "لوحة تحكم المشرف",
    addProd: "إضافة إنتاج",
    prodName: "اسم الإنتاج",
    prodCoord: "اسم المنسق",
    prodEmail: "البريد الإلكتروني",
    invite: "دعوة",
    status: "الحالة",
    logout: "تسجيل الخروج",
    thankYou: "شكراً لك!",
    voteRegistered: "تم تسجيل تعليقك.",
    alreadyVoted: "تم استلام التعليق",
    alreadyVotedDesc: "لقد قدمت بالفعل تعليقًا لهذا اليوم.",
    viewStats: "الإحصائيات",
    prodStats: "إحصائيات الإنتاج",
    currentScore: "النتيجة الحالية",
    recentIncidents: "الحوادث الأخيرة",
    noIncidents: "لم يتم الإبلاغ عن حوادث حرجة.",
    close: "إغلاق",
    manage: "إدارة",
    manageProd: "إدارة الإنتاج",
    endProd: "إنهاء الإنتاج",
    reactivateProd: "إعادة تنشيط",
    prodEnded: "انتهى الإنتاج",
    teamMembers: "وصول الفريق",
    addMember: "إضافة عضو فريق",
    roleLabel: "الدور",
    nameLabel: "الاسم",
    emailLabel: "البريد الإلكتروني",
    add: "إضافة",
    maxMembers: "تم الوصول للحد الأقصى",
    generalInfo: "معلومات عامة",
    edit: "تعديل",
    save: "حفظ",
    cancel: "إلغاء",
    inviteSent: "تم إرسال الدعوة!",
    registerProd: "تسجيل إنتاج جديد",
    regTitle: "التسجيل الرسمي",
    regDesc: "قدم تفاصيل إنتاجك للتحقق والتنشيط.",
    countryLabel: "البلد",
    selectCountry: "اختر البلد",
    otherCountryPlaceholder: "أدخل البلد",
    period: "فترة الإنتاج",
    periodStart: "من (MM/YYYY)",
    periodEnd: "إلى (MM/YYYY)",
    officeAddr: "عنوان المكتب",
    billingAddr: "عنوان الفواتير",
    trustSection: "جهة اتصال السلامة",
    optional: "(اختياري)",
    trustThemis: "شريك Themis",
    trustInternal: "جهة اتصال داخلية",
    trustInternalName: "معلومات الاتصال",
    regSuccess: "تم تقديم الطلب بنجاح",
    regSuccessDesc: "تم استلام بياناتك. سيقوم فريقنا بالتحقق وتنشيط الإنتاج خلال 24 ساعة.",
    tabSchedule: "الجدول",
    tabDetails: "التفاصيل",
    landHero: "مواقع تصوير آمنة.",
    landSub: "البرنامج المتخصص لمكافحة التحرش في مواقع التصوير وتخفيف عبء العمل عن مديري الإنتاج.",
    landCTA: "ابدأ الآن",
    feat1Title: "تعليقات مجهولة",
    feat1Desc: "تمكين طاقمك.",
    feat1More: "تشفير متقدم.",
    feat2Title: "رؤى فورية",
    feat2Desc: "راقب الجو.",
    feat2More: "مقاييس لوحة التحكم.",
    feat3Title: "آمن وموثوق",
    feat3Desc: "متوافق مع GDPR.",
    feat3More: "معايير صارمة.",
    howTitle: "كيف يعمل",
    how1: "سجل",
    how2: "اطبع QR",
    how3: "صوت",
    trustBadge1: "الإصدار 2.0 • جديد 2026",
    trustBadge2: "مباشر الآن في المملكة المتحدة والإمارات وألمانيا وعبر الاتحاد الأوروبي.",
    trustSecTitle: "لست وحدك أبدًا.",
    trustSecSub: "الدعم متكامل.",
    trustSecFeat1: "اتصال Themis.",
    trustSecFeat2: "متاح 24/7.",
    trustSecFeat3: "خط ساخن.",
    trustCardTitle: "مركز الثقة",
    trustCardName: "مركز Themis",
    trustCardBtn: "اتصل بالدعم",
    deptInsights: "رؤى الأقسام",
    markResolved: "حل التعليق",
    testAccess: "Test Access",
    enterTestCode: "Enter Code",
    requestTestAccess: "Request Access",
    pendingRequests: "Access Requests",
    approve: "Approve",
    reject: "Reject",
    testAccountInfo: "Test Account. No data saved."
  }
};
