
import { Translation, Language, Production } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    appSub: "Safe on Set",
    role: "Production Manager",
    hMood: "LIVE MOOD",
    hTrend: "TREND HISTORY",
    hAccess: "ACCESS & ACTIONS",
    pdf: "PDF",
    email: "Email",
    inbox: "Feedback",
    inboxTitle: "Written Feedback",
    mobTitle: "TODAY'S FEEDBACK",
    mobQuest: "How did you feel about today's shoot?",
    happy: "Happy 😊",
    stress: "Stressed 😓",
    submit: "Submit",
    compTitle: "⚠️ We are sorry to hear that.",
    compDesc: "Please tell us what happened so we can help.",
    compContact: "Contact (Required)",
    alert: "Feedback submitted!",
    dir: "ltr",
    day: "Day",
    today: "Today",
    explTitle100: "Status: Excellent",
    explText100: "Everything is in order, crew feels well.",
    explTitle90: "Status: Attention Required",
    explText90: "Negative feedback received recently. Action required - please review written feedback.",
    explTitle80: "Status: Urgent Action",
    explText80: "Immediate action required - multiple negative feedbacks received.",
    imprBtn: "Legal Notice",
    imprTitle: "Legal Notice",
    imprText: "Information according to § 5 TMG:\n\nTrustory GmbH\nRathausgasse 5\n12529 Schönefeld\nGermany\n\nRepresented by:\nMax Mustermann\n\nContact:\nPhone: +49 (0) 3379 9976627\nEmail: info@safe-on-set.com\n\nRegister Entry:\nEntry in the Commercial Register.\nRegister Court: Amtsgericht Cottbus\nRegister Number: HRB 12345\n\nVAT ID:\nSales tax identification number according to §27 a sales tax law:\nDE 123456789",
    privacyTitle: "Privacy Policy",
    privacyText: "1. Data Protection at a Glance\n\nGeneral Information\nThe following notes provide a simple overview of what happens to your personal data when you visit this website. Personal data is all data with which you can be personally identified.\n\nData Collection on this Website\nWho is responsible for data collection on this website?\nThe data processing on this website is carried out by the website operator: Trustory GmbH. You can find their contact details in the section \"Information on the Responsible Party\" in this privacy policy.\n\nHow do we collect your data?\nYour data is collected when you provide it to us. This can be, for example, data you enter in a contact form. Other data is collected automatically or after your consent when visiting the website by our IT systems. This is mainly technical data (e.g., internet browser, operating system, or time of page view).\n\n2. Hosting\nWe host the content of our website with the following provider: AWS (Germany).",
    termsTitle: "Terms of Service",
    termsText: "1. Scope\nThese General Terms and Conditions (GTC) apply to all business relationships between Trustory GmbH (hereinafter: Provider) and its customers for the product \"Safe on Set\".\n\n2. Subject of the Contract\nThe Provider offers a SaaS solution for mood tracking in film productions. The exact scope of services is derived from the current service description on the website.\n\n3. Registration & Access\nUse requires registration. The customer is obliged to provide truthful information. Access data must be kept secret.\n\n4. Data Protection & Confidentiality\nThe Provider undertakes to treat all transmitted data confidentially and to use it exclusively for the purpose of fulfilling the contract.\n\n5. Limitation of Liability\nThe Provider is liable for intent and gross negligence. Liability for slight negligence is excluded, provided that no essential contractual obligations are violated.",
    votingClosed: "Voting Closed",
    votingClosedDesc: "Today is not a scheduled shooting day.",
    btnPositive: "EVERYTHING IS FINE",
    btnNegative: "NEGATIVE EXPERIENCE",
    disclaimerText: "Did you feel comfortable on set / in the production office today and have you not experienced or observed sexual harassment, bullying, racism, or similar? If yes, please confirm that you felt comfortable. If no, please share that you have experienced or observed negative situations.",
    selectDept: "Select Department (Optional)",
    deptLabel: "Department",
    depts: {
      production: "Production",
      direction: "Direction",
      camera: "Camera",
      lighting: "Lighting / Grip",
      sound: "Sound",
      art: "Art Dept / Props",
      costume: "Costume",
      makeup: "Hair & Makeup",
      catering: "Catering",
      cast: "Cast / Stunts",
      other: "Other"
    },
    adminLogin: "Admin Login",
    otpSent: "Code sent to email!",
    otpPlaceholder: "Enter 6-digit Code",
    sendCode: "Send Code",
    verifyCode: "Verify & Login",
    backToEmail: "Change Email",
    adminDash: "Admin Dashboard",
    addProd: "Add Production",
    prodName: "Production Name",
    prodCoord: "Coordinator Name",
    prodEmail: "Coordinator Email",
    invite: "Invite",
    status: "Status",
    logout: "Logout",
    thankYou: "Thank You!",
    voteRegistered: "Your feedback has been registered.",
    alreadyVoted: "Feedback Received",
    alreadyVotedDesc: "You have already submitted feedback for today.",
    viewStats: "Stats",
    prodStats: "Production Statistics",
    currentScore: "Current Score",
    recentIncidents: "Recent Incidents",
    noIncidents: "No critical incidents reported.",
    close: "Close",
    manage: "Manage",
    manageProd: "Manage Production",
    endProd: "End Production",
    reactivateProd: "Reactivate",
    prodEnded: "Production Finished",
    teamMembers: "Team Access",
    addMember: "Add Team Member",
    roleLabel: "Role",
    nameLabel: "Name",
    emailLabel: "Email",
    add: "Add",
    maxMembers: "Max 4 additional members reached",
    generalInfo: "General Information",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    inviteSent: "Invitation sent!",
    registerProd: "Register New Production",
    regTitle: "Production Registration",
    regDesc: "Register your production. Your account will be reviewed by an admin.",
    countryLabel: "Production Country",
    selectCountry: "Select Country",
    otherCountryPlaceholder: "Enter Country Name",
    period: "Shooting Period",
    periodStart: "Start Date",
    periodEnd: "End Date",
    officeAddr: "Production Office Address",
    billingAddr: "Billing Address",
    trustSection: "Trust & Safety Contact",
    optional: "(Optional)",
    trustThemis: "We work with Themis",
    trustInternal: "Internal Trust Contact",
    trustInternalName: "Name / Email / Phone",
    regSuccess: "Registration Submitted",
    regSuccessDesc: "Your request has been sent to our admins. You will receive an email once your account is active.",
    tabSchedule: "Shooting Schedule",
    tabDetails: "Production Details",
    landHero: "Safe Sets. Better Stories.",
    landSub: "The modern standard for mood tracking and crew well-being in film production.",
    landCTA: "Start Your Production",
    feat1Title: "Anonymous Feedback",
    feat1Desc: "Empower your crew to voice concerns without fear.",
    feat1More: "Our advanced encryption ensures that no metadata is stored that could identify a user.",
    feat2Title: "Real-Time Insights",
    feat2Desc: "Monitor set atmosphere instantly and act fast.",
    feat2More: "Dashboard metrics update the moment a vote is cast.",
    feat3Title: "Secure & Trusted",
    feat3Desc: "GDPR compliant and trusted by industry leaders.",
    feat3More: "We adhere to the strictest data protection standards (GDPR).",
    howTitle: "How it works",
    how1: "Register Production",
    how2: "Print QR Code",
    how3: "Crew Scans & Votes",
    trustBadge1: "Version 2.0 • New from 2026",
    trustBadge2: "Used globally. Trusted by major streamers.",
    trustSecTitle: "Never Alone.",
    trustSecSub: "Professional support is integrated directly into the system.",
    trustSecFeat1: "Direct connection to Themis or internal trust persons.",
    trustSecFeat2: "24/7 availability for critical incidents.",
    trustCardTitle: "Trust Center",
    trustCardName: "Themis Advice Center",
    trustCardBtn: "Contact Confidential Support"
  },
  de: {
    appSub: "Safe on Set",
    role: "Produktionsleitung",
    hMood: "AKTUELLE STIMMUNG",
    hTrend: "TREND VERLAUF",
    hAccess: "ZUGANG & AKTIONEN",
    pdf: "PDF",
    email: "Senden",
    inbox: "Feedback",
    inboxTitle: "Schriftliches Feedback",
    mobTitle: "HEUTIGES FEEDBACK",
    mobQuest: "Wie hast du den heutigen Drehtag empfunden?",
    happy: "Zufrieden 😊",
    stress: "Gestresst 😓",
    submit: "Absenden",
    compTitle: "⚠️ Das tut uns leid.",
    compDesc: "Bitte sag uns was passiert ist, damit wir helfen können.",
    compContact: "Kontakt (Erforderlich)",
    alert: "Feedback gesendet!",
    dir: "ltr",
    day: "Tag",
    today: "Heute",
    explTitle100: "Status: Ausgezeichnet",
    explText100: "Alles ist in Ordnung, Mitarbeiter fühlen sich wohl.",
    explTitle90: "Status: Aufmerksamkeit erforderlich",
    explText90: "Ein negatives Feedback wurde kürzlich abgegeben.",
    explTitle80: "Status: Dringende Aktion",
    explText80: "Sofortige Aktion erforderlich.",
    imprBtn: "Impressum",
    imprTitle: "Impressum",
    imprText: "Angaben gemäß § 5 TMG:\n\nTrustory GmbH\nRathausgasse 5\n12529 Schönefeld\nDeutschland\n\nRepresented by:\nMax Mustermann\n\nKontakt:\nTelefon: +49 (0) 3379 9976627\nE-Mail: info@safe-on-set.com\n\nRegistereintrag:\nEintragung im Handelsregister.\nRegistergericht: Amtsgericht Cottbus\nRegisternummer: HRB 12345",
    privacyTitle: "Datenschutzerklärung",
    privacyText: "Datenschutzhinweise für das Produkt Safe on Set der Trustory GmbH.",
    termsTitle: "AGB",
    termsText: "Allgemeine Geschäftsbedingungen der Trustory GmbH für Safe on Set.",
    votingClosed: "Abstimmung Geschlossen",
    votingClosedDesc: "Heute ist kein geplanter Drehtag.",
    btnPositive: "ALLES IN ORDNUNG",
    btnNegative: "NEGATIVE ERFAHRUNG",
    disclaimerText: "Hast du dich heute am Set / Produktionsbüro wohlgefühlt?",
    selectDept: "Abteilung wählen (Optional)",
    deptLabel: "Abteilung",
    depts: {
      production: "Produktion",
      direction: "Regie",
      camera: "Kamera",
      lighting: "Licht / Bühne",
      sound: "Ton",
      art: "Szenenbild / Requisite",
      costume: "Kostüm",
      makeup: "Maske",
      catering: "Catering",
      cast: "Darsteller / Stunts",
      other: "Sonstiges"
    },
    adminLogin: "Admin Login",
    otpSent: "Code an Email gesendet!",
    otpPlaceholder: "6-stelligen Code eingeben",
    sendCode: "Code anfordern",
    verifyCode: "Verifizieren & Login",
    backToEmail: "Email ändern",
    adminDash: "Admin Übersicht",
    addProd: "Produktion anlegen",
    prodName: "Produktions-Titel",
    prodCoord: "Name Koordinator/in",
    prodEmail: "Email Koordinator/in",
    invite: "Einladen",
    status: "Status",
    logout: "Abmelden",
    thankYou: "Danke!",
    voteRegistered: "Dein Feedback wurde registriert.",
    alreadyVoted: "Feedback erhalten",
    alreadyVotedDesc: "Du hast heute bereits Feedback abgegeben.",
    viewStats: "Statistik",
    prodStats: "Produktions-Statistik",
    currentScore: "Aktueller Score",
    recentIncidents: "Kürzliche Vorfälle",
    noIncidents: "Keine kritischen Vorfälle gemeldet.",
    close: "Schließen",
    manage: "Verwalten",
    manageProd: "Produktion verwalten",
    endProd: "Produktion beenden",
    reactivateProd: "Reaktivieren",
    prodEnded: "Produktion beendet",
    teamMembers: "Team Zugang",
    addMember: "Team-Mitglied hinzufügen",
    roleLabel: "Rolle",
    nameLabel: "Name",
    emailLabel: "Email",
    add: "Hinzufügen",
    maxMembers: "Maximal 4 weitere Mitglieder erreicht",
    generalInfo: "Allgemeine Informationen",
    edit: "Bearbeiten",
    save: "Speichern",
    cancel: "Abbrechen",
    inviteSent: "Einladung gesendet!",
    registerProd: "Neue Produktion Registrieren",
    regTitle: "Produktion Registrieren",
    regDesc: "Registriere deine Produktion.",
    countryLabel: "Produktionsland",
    selectCountry: "Land wählen",
    otherCountryPlaceholder: "Land eingeben",
    period: "Produktionszeitraum",
    periodStart: "Startdatum",
    periodEnd: "Enddatum",
    officeAddr: "Anschrift Produktionsbüro",
    billingAddr: "Rechnungsanschrift",
    trustSection: "Vertrauensstelle / Ansprechpartner",
    optional: "(Optional)",
    trustThemis: "Wir arbeiten mit der Themis zusammen",
    trustInternal: "Interne Vertrauensperson",
    trustInternalName: "Name / Email / Telefon",
    regSuccess: "Registrierung eingereicht",
    regSuccessDesc: "Deine Anfrage wurde gesendet.",
    tabSchedule: "Drehplan",
    tabDetails: "Produktionsdaten",
    landHero: "Sichere Sets. Bessere Filme.",
    landSub: "Der moderne Standard für Stimmungsbarometer und Crew-Wohlbefinden.",
    landCTA: "Produktion Starten",
    feat1Title: "Anonymes Feedback",
    feat1Desc: "Ermögliche der Crew, Bedenken ohne Angst zu äußern.",
    feat1More: "Anonymität ist garantiert.",
    feat2Title: "Echtzeit-Einblicke",
    feat2Desc: "Überwache die Set-Atmosphäre sofort.",
    feat2More: "Daten-Updates in Echtzeit.",
    feat3Title: "Sicher & Vertrauenswürdig",
    feat3Desc: "DSGVO-konform.",
    feat3More: "Sicheres Hosting in Deutschland.",
    howTitle: "So funktioniert's",
    how1: "Produktion Registrieren",
    how2: "QR-Code Drucken",
    how3: "Crew Scan & Vote",
    trustBadge1: "Version 2.0 • Neu ab 2026",
    trustBadge2: "Global eingesetzt. Vertraut von Streamern.",
    trustSecTitle: "Niemals Allein.",
    trustSecSub: "Professionelle Unterstützung integriert.",
    trustSecFeat1: "Direkte Einbindung von Themis.",
    trustSecFeat2: "24/7 Erreichbarkeit.",
    trustCardTitle: "Vertrauensstelle",
    trustCardName: "Themis Beratungsstelle",
    trustCardBtn: "Vertrauliche Hilfe Kontaktieren"
  },
  ar: {
    appSub: "Safe on Set",
    role: "مدير الإنتاج",
    hMood: "الحالة المزاجية المباشرة",
    hTrend: "تاريخ الاتجاهات",
    hAccess: "الوصول والإجراءات",
    pdf: "PDF",
    email: "البريد الإلكتروني",
    inbox: "التعليقات",
    inboxTitle: "التعليقات المكتوبة",
    mobTitle: "تعليقات اليوم",
    mobQuest: "كيف شعرت تجاه تصوير اليوم؟",
    happy: "سعيد 😊",
    stress: "مضغوط 😓",
    submit: "إرسال",
    compTitle: "⚠️ نأسف لسماع ذلك.",
    compDesc: "يرجى إخبارنا بما حدث لنتمكن من المساعدة.",
    compContact: "الاتصال (مطلوب)",
    alert: "تم إرسال التعليق!",
    dir: "rtl",
    day: "يوم",
    today: "اليوم",
    explTitle100: "الحالة: ممتاز",
    explText100: "كل شيء على ما يرام، الطاقم يشعر بالراحة.",
    explTitle90: "الحالة: انتباه مطلوب",
    explText90: "تم استلام تعليقات سلبية مؤخرًا. يرجى مراجعة التعليقات المكتوبة.",
    explTitle80: "الحالة: إجراء عاجل",
    explText80: "مطلوب إجراء فوري - تم استلام عدة تعليقات سلبية.",
    imprBtn: "إشعار قانوني",
    imprTitle: "إشعار قانوني",
    imprText: "Trustory GmbH",
    privacyTitle: "سياسة الخصوصية",
    privacyText: "1. حماية البيانات باختصار...",
    termsTitle: "شروط الخدمة",
    termsText: "1. النطاق...",
    votingClosed: "التصويت مغلق",
    votingClosedDesc: "اليوم ليس يوم تصوير مجدول.",
    btnPositive: "كل شيء على ما يرام",
    btnNegative: "تجربة سلبية",
    disclaimerText: "هل شعرت بالراحة في موقع التصوير / مكتب الإنتاج اليوم ولم تتعرض أو تلاحظ أي تحرش أو تنمر أو عنصرية؟",
    selectDept: "اختر القسم (اختياري)",
    deptLabel: "القسم",
    depts: {
      production: "الإنتاج",
      direction: "الإخراج",
      camera: "الكاميرا",
      lighting: "الإضاءة / المقابض",
      sound: "الصوت",
      art: "قسم الفن / الإكسسوارات",
      costume: "الملابس",
      makeup: "الشعر والمكياج",
      catering: "التغذية",
      cast: "الممثلون / البدلاء",
      other: "آخر"
    },
    adminLogin: "تسجيل دخول المشرف",
    otpSent: "تم إرسال الرمز إلى البريد الإلكتروني!",
    otpPlaceholder: "أدخل الرمز المكون من 6 أرقام",
    sendCode: "إرسال الرمز",
    verifyCode: "التحقق والدخول",
    backToEmail: "تغيير البريد الإلكتروني",
    adminDash: "لوحة تحكم المشرف",
    addProd: "إضافة إنتاج",
    prodName: "اسم الإنتاج",
    prodCoord: "اسم المنسق",
    prodEmail: "البريد الإلكتروني للمنسق",
    invite: "دعوة",
    status: "الحالة",
    logout: "تسجيل الخروج",
    thankYou: "شكراً لك!",
    voteRegistered: "تم تسجيل تعليقك.",
    alreadyVoted: "تم استلام التعليق",
    alreadyVotedDesc: "لقد قمت بالفعل بتقديم تعليق لهذا اليوم.",
    viewStats: "الإحصائيات",
    prodStats: "إحصائيات الإنتاج",
    currentScore: "النتيجة الحالية",
    recentIncidents: "الحوادث الأخيرة",
    noIncidents: "لم يتم الإبلاغ عن حوادث حرجة.",
    close: "إغلاق",
    manage: "إدارة",
    manageProd: "إدارة الإنتاج",
    endProd: "إنهاء الإنتاج",
    reactivateProd: "إعادة تنشيط",
    prodEnded: "انتهى الإنتاج",
    teamMembers: "وصول الفريق",
    addMember: "إضافة عضو فريق",
    roleLabel: "الدور",
    nameLabel: "الاسم",
    emailLabel: "البريد الإلكتروني",
    add: "إضافة",
    maxMembers: "تم الوصول إلى الحد الأقصى (4 أعضاء إضافيين)",
    generalInfo: "معلومات عامة",
    edit: "تعديل",
    save: "حفظ",
    cancel: "إلغاء",
    inviteSent: "تم إرسال الدعوة!",
    registerProd: "تسجيل إنتاج جديد",
    regTitle: "تسجيل الإنتاج",
    regDesc: "سجل إنتاجك. سيقوم المشرف بمراجعة حسابك.",
    countryLabel: "بلد الإنتاج",
    selectCountry: "اختر البلد",
    otherCountryPlaceholder: "أدخل اسم البلد",
    period: "فترة التصوير",
    periodStart: "تاريخ البدء",
    periodEnd: "تاريخ الانتهاء",
    officeAddr: "عنوان مكتب الإنتاج",
    billingAddr: "عنوان الفواتير",
    trustSection: "جهة اتصال الثقة والسلامة",
    optional: "(اختياري)",
    trustThemis: "نحن نعمل مع Themis",
    trustInternal: "جهة اتصال ثقة داخلية",
    trustInternalName: "الاسم / البريد الإلكتروني / الهاتف",
    regSuccess: "تم تقديم التسجيل",
    regSuccessDesc: "تم إرسال طلبك إلى مشرفينا. ستتلقى بريدًا إلكترونيًا بمجرد تفعيل حسابك.",
    tabSchedule: "جدول التصوير",
    tabDetails: "تفاصيل الإنتاج",
    landHero: "مواقع تصوير آمنة. قصص أفضل.",
    landSub: "المعيار الحديث لتتبع الحالة المزاجية ورفاهية الطاقم في إنتاج الأفلام.",
    landCTA: "ابدأ إنتاجك",
    feat1Title: "تعليقات مجهولة",
    feat1Desc: "تمكين طاقمك من التعبير عن مخاوفهم دون خوف.",
    feat1More: "يضمن تشفيرنا المتقدم عدم تخزين أي بيانات وصفية يمكن أن تحدد هوية المستخدم.",
    feat2Title: "رؤى في الوقت الحقيقي",
    feat2Desc: "راقب جو موقع التصوير فورًا وتحرك بسرعة.",
    feat2More: "تتحدث مقاييس لوحة التحكم فور الإدلاء بصوت.",
    feat3Title: "آمن وموثوق",
    feat3Desc: "متوافق مع GDPR وموثوق به من قبل قادة الصناعة.",
    feat3More: "نحن نلتزم بأعلى معايير حماية البيانات (GDPR).",
    howTitle: "كيف يعمل",
    how1: "تسجيل الإنتاج",
    how2: "طباعة رمز QR",
    how3: "الطاقم يمسح ويصوت",
    trustBadge1: "الإصدار 2.0 • جديد من 2026",
    trustBadge2: "يستخدم عالمياً. موثوق به من قبل كبرى شركات البث.",
    trustSecTitle: "لست وحدك أبدًا.",
    trustSecSub: "الدعم المهني متكامل مباشرة في النظام.",
    trustSecFeat1: "اتصال مباشر مع Themis أو أشخاص ثقة داخليين.",
    trustSecFeat2: "متاح 24/7 للحوادث الحرجة.",
    trustCardTitle: "مركز الثقة",
    trustCardName: "مركز استشارات Themis",
    trustCardBtn: "اتصل بالدعم السري"
  }
};

export const INITIAL_SCHEDULE: any[] = [
  { day: 24, date: new Date().toISOString().split('T')[0] },
  { day: 23, date: new Date(Date.now() - 86400000).toISOString().split('T')[0] },
  { day: 22, date: new Date(Date.now() - 172800000).toISOString().split('T')[0] }
];

export const INITIAL_PRODUCTIONS: Production[] = [
  { id: '1', name: 'Safe on Set Pilot', coordinator: 'Max Mustermann', email: 'admin@safe-on-set.com', status: 'Active', team: [] },
  { id: '2', name: 'TATORT Berlin', coordinator: 'Lisa Müller', email: 'lisa@prod.com', status: 'Pending', team: [] },
];
